sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345
  alioss:
    endpoint: ${SKY_ALIOSS_ENDPOINT:oss-cn-shanghai.aliyuncs.com}
    access-key-id: ${SKY_ALIOSS_ACCESS_KEY_ID}
    access-key-secret: ${SKY_ALIOSS_ACCESS_KEY_SECRET}
    bucket-name: ${SKY_ALIOSS_BUCKET_NAME:sattis-photo}
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: ${SKY_WECHAT_APPID}
    secret: ${SKY_WECHAT_SECRET}